replicaCount: 1
image:
  repository: ghcr.io/abinashgit051/myapp101:1.0.0
  pullPolicy: IfNotPresent
  tag: "1.0.0"


nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

service:
  type: NodePort
  port: 80
  nodePort: 31231

